name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-gcc-10
      run: |
         sudo apt update
         sudo apt install gcc-10 g++-10
      shell: bash
    - name: make
      run: make -C UnitTest CXX=g++-10
