name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: install-gcc-12
      run: |
         sudo apt update
         sudo apt install gcc-12 g++-12
      shell: bash
    - name: make
      run: make -C UnitTest CXX=g++-12 all
    - name: test
      run: ./bin/UnitTest
